version: '2'

services:
  flask:
    build: ./
    container_name: flask-vue
    volumes:
      - ./:/var/www/
      - socket:/var/tmp
      - ./log/:/var/log/
    environment:
      TZ: 'Asia/Tokyo'
      WORK_DIR: '/var/www'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - socket:/var/tmp
      - ./log/nginx/:/var/log/nginx/
    links:
      - flask
    ports:
      - '3001:3001'
    environment:
      TZ: 'Asia/Tokyo'

volumes:
  socket:
    driver: 'local'
